version: '3.7'

services:
  web:
    build: ./app
    # command: gunicorn cf.wsgi:application --bind 0.0.0.0:80
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    environment:
      - DJANGO_SUPERUSER_PASSWORD=superuser
      - DEBUG=1
      - SECRET_KEY=a';k'm'a;gjobhvwliaugfkbugcrlaiuf'ctkpo'mqt'
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] *
