# Generated by Django 3.2.5 on 2021-08-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210804_0556'),
        ('suppliers', '0002_auto_20210722_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='tag',
        ),
        migrations.AddField(
            model_name='supplier',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
