# Generated by Django 3.2.5 on 2021-07-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
