# Generated by Django 3.2.5 on 2021-07-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20210722_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='district',
            field=models.CharField(choices=[('Gros Islet', 'Gros Islet'), ('Castries', 'Castries'), ('Soufriere', 'Soufriere'), ('Vieux Fort', 'Vieux Fort')], default='castries', max_length=25),
        ),
    ]
