# Generated by Django 3.2.5 on 2021-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_auto_20210722_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='district',
            field=models.CharField(choices=[('Gros Islet', 'Gros Islet'), ('Castries', 'Castries'), ('Soufriere', 'Soufriere'), ('Vieux Fort', 'Vieux Fort')], default='Castries', max_length=25),
        ),
    ]
