# Generated by Django 3.2.5 on 2021-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_qty_product_init_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='init_qty',
            field=models.IntegerField(default=0, verbose_name='initial quantity'),
        ),
    ]
