# Generated by Django 3.2.5 on 2021-07-22 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default='3D1DF4B13889', max_length=20, unique=True)),
                ('qty', models.IntegerField(default=0)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_from', models.CharField(blank=True, max_length=100, null=True)),
                ('received_comment', models.TextField(blank=True, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to=orders.models.purchase_order_path)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.product')),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
