# Generated by Django 3.2.5 on 2021-07-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='A6D4B448150C', editable=False, max_length=20),
        ),
    ]
