# Generated by Django 3.2.5 on 2021-07-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='91E711BD0EE5', editable=False, max_length=20),
        ),
    ]
