# Generated by Django 3.2.5 on 2021-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='57E73EB32FEA', editable=False, max_length=20),
        ),
    ]
