# Generated by Django 3.2.5 on 2021-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='9B6F5994FA66', editable=False, max_length=20),
        ),
    ]
