# Generated by Django 3.2.5 on 2021-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='1A815DF411A1', editable=False, max_length=20),
        ),
    ]
