# Generated by Django 3.2.5 on 2021-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='5806CE454B86', editable=False, max_length=20),
        ),
    ]
