# Generated by Django 3.2.5 on 2021-07-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
    ]
