# Generated by Django 3.2.5 on 2021-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='uid',
            field=models.CharField(default='6F8727455861', editable=False, max_length=20),
        ),
    ]
