# Generated by Django 3.2.5 on 2021-07-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_delivery_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='uid',
            field=models.CharField(default='5E2F6F1B3DB1', editable=False, max_length=20),
        ),
    ]
