# Generated by Django 3.2.5 on 2021-07-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_delivery_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='uid',
            field=models.CharField(default='8625899E13D6', editable=False, max_length=20),
        ),
    ]
