# Generated by Django 3.2.5 on 2021-07-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_delivery_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='uid',
        ),
    ]
