# Generated by Django 3.2.5 on 2021-07-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_deputy_commissioner',
            new_name='is_ag',
        ),
    ]
