# Generated by Django 3.2.5 on 2021-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210723_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_ag',
            field=models.BooleanField(default=False, verbose_name='AG'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_seo',
            field=models.BooleanField(default=False, verbose_name='SEO'),
        ),
    ]
